@startuml

' Install PlantUML plugin for IntelliJ IDEA to render this.
' Full PlantUML usage at http://plantuml.com/commons

skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor yellow

title Kafka example explained

participant PollConsumer as pc
participant StreamConsumer as sc
participant TestProducer as tp
participant Kafka as k << test-topic >>

loop 1000 times
    tp -> k : post message to test-topic
    tp -> tp : print timing info
end

group consumers
    loop
        sc <- k : stream from test-topic
        sc -> sc : print message details
    end
    loop
        pc <- k : poll from test-topic
        pc -> pc : print message details
    end
end

@enduml